// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmkbhaqphvxtsvhmpsls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpta2JoYXFwaHZ4dHN2aG1wc2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDAxNDYsImV4cCI6MjA1OTI3NjE0Nn0.z4ltelA41lplwqQO2UqR7DlWX7WYWkbrtaFYT0augA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);